# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addItemtoSupp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Backend import loadAvailableItemToSupp
from Utils import widgetTablesTools, messageBox
from Utils.database import database


class Ui_Dialog(object):
    def setupUi(self, Dialog, callback: callable, sup_id: str):
        self.sup_id = sup_id
        Dialog.setObjectName("Dialog")
        Dialog.resize(1252, 721)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(900, 680, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(10, 10, 1231, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.supplieView = QtWidgets.QTableWidget(Dialog)
        self.supplieView.setGeometry(QtCore.QRect(10, 70, 1231, 601))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.supplieView.setFont(font)
        self.supplieView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.supplieView.setAlternatingRowColors(True)
        self.supplieView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.supplieView.setObjectName("supplieView")

        def _callback():
            # print([s.text() for s in ])
            # print(widgetTablesTools.get_selected_row_data(self.supplieView))
            ids = [li[0] for li in widgetTablesTools.get_selected_row_data(self.supplieView)]
            attempt = True

            for _id in ids:
                attempt = database.execNonQuery('INSERT INTO SUPPLIER_ITEM_LISTS (SUPP_ID, ITEM_ID, STAT) VALUES (%s, %s, 1)', (self.sup_id, _id))
                if not attempt:
                    break;
            
            if(len(ids) < 1):
                Dialog.reject()
            elif attempt:
                messageBox.Message("Success", ("Items" if len(ids) > 1 else "Item") +" added to Supplier's Available Item Successfully")
            else:
                messageBox.Message("Fail", "Database Internal Error")
                

            callback()
            Dialog.accept()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(_callback) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Item List"))
        self.title.setText(_translate("Dialog", "Add Item"))
        loadAvailableItemToSupp.initial(self.sup_id, self.supplieView)



def start(callback: callable, sup_id):
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, callback, sup_id)
    Dialog.exec_()
