# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os, sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from Utils.database import database
from Utils import messageBox


class Ui_AddItem(object):
    def setupUi(self, AddItem, callback: callable):
        AddItem.setObjectName("AddItem")
        AddItem.resize(466, 244)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddItem)
        self.buttonBox.setGeometry(QtCore.QRect(10, 200, 441, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.ItemName = QtWidgets.QLineEdit(AddItem)
        self.ItemName.setMaxLength(100)
        self.ItemName.setGeometry(QtCore.QRect(20, 50, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ItemName.setFont(font)
        self.ItemName.setObjectName("ItemName")
        self.label = QtWidgets.QLabel(AddItem)
        self.label.setGeometry(QtCore.QRect(20, 30, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddItem)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(AddItem)
        self.doubleSpinBox.setGeometry(QtCore.QRect(20, 140, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setObjectName("doubleSpinBox")

        def _callback():
            # saving here
            attempt = database.execNonQuery('INSERT INTO item_info (`name`, base_price) VALUES (%s, %s)', (self.ItemName.text(), self.doubleSpinBox.text()))

            if attempt:
                messageBox.Message("Success", "Item Added Successfully")
            else:
                messageBox.Message("Fail", "Database Internal Error")
    
            callback()
            AddItem.accept()

        self.retranslateUi(AddItem)
        # self.buttonBox.accepted.connect(AddItem.accept) # type: ignore
        self.buttonBox.accepted.connect(_callback) # type: ignore
        self.buttonBox.rejected.connect(AddItem.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddItem)
        self.doubleSpinBox.setMaximum(1677216.99)

    def retranslateUi(self, AddItem):
        _translate = QtCore.QCoreApplication.translate
        AddItem.setWindowTitle(_translate("AddItem", "Add Item"))
        self.label.setText(_translate("AddItem", "Product Name"))
        self.label_2.setText(_translate("AddItem", "Price"))


def start(callback: callable):
    Dialog = QtWidgets.QDialog()
    ui = Ui_AddItem()
    ui.setupUi(Dialog, callback)
    Dialog.exec_()
