# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addSupplier.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import os, sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from Utils.database import database
from Utils import messageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog, callback: callable):
        Dialog.setObjectName("Dialog")
        Dialog.resize(614, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 571, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.supplierName = QtWidgets.QLineEdit(Dialog)
        self.supplierName.setMaxLength(100)
        self.supplierName.setGeometry(QtCore.QRect(20, 40, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.supplierName.setFont(font)
        self.supplierName.setText("")
        self.supplierName.setObjectName("ItemName")
        self.address = QtWidgets.QLineEdit(Dialog)
        self.address.setMaxLength(150)
        self.address.setGeometry(QtCore.QRect(20, 110, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.address.setFont(font)
        self.address.setText("")
        self.address.setObjectName("ItemName_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.remarks = QtWidgets.QLineEdit(Dialog)
        self.remarks.setMaxLength(150)
        self.remarks.setGeometry(QtCore.QRect(20, 170, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.remarks.setFont(font)
        self.remarks.setText("")
        self.remarks.setObjectName("ItemName_3")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(20, 220, 221, 17))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")


        def _callback():
            # saving here
            attempt = database.execNonQuery("INSERT INTO supplier_info (supplier_name, address, remarks, stat) VALUES (%s, %s, %s, %s)", 
                                            (self.supplierName.text(), self.address.text(), self.remarks.text() or '', '1' if self.checkBox.isChecked() else '0'))
            
            if attempt:
                messageBox.Message("Success", "Supplier Added Successfully")
            else:
                messageBox.Message("Fail", "Database Internal Error")
    
            callback()
            Dialog.accept()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(_callback) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Supplier"))
        self.label_2.setText(_translate("Dialog", "Address"))
        self.label_3.setText(_translate("Dialog", "Remarks"))
        self.checkBox.setText(_translate("Dialog", "Active Supplier"))


def start(callback: callable):
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, callback)
    Dialog.exec_()
