# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os, sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from Backend import loadItemInfo, loadSupplierInfo, dashboardBtnConfigs

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ms(object):
    def setupUi(self, Ms):
        Ms.setObjectName("Ms")
        Ms.resize(1240, 720)
        Ms.setMinimumSize(QtCore.QSize(1240, 720))
        Ms.setMaximumSize(QtCore.QSize(1240, 720))
        self.centralwidget = QtWidgets.QWidget(Ms)
        self.centralwidget.setObjectName("centralwidget")
        self.addSupplier = QtWidgets.QPushButton(self.centralwidget)
        self.addSupplier.setGeometry(QtCore.QRect(930, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addSupplier.setFont(font)
        self.addSupplier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addSupplier.setStyleSheet("")
        self.addSupplier.setAutoDefault(True)
        self.addSupplier.setDefault(True)
        self.addSupplier.setFlat(False)
        self.addSupplier.setObjectName("addSupplier")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.addItem = QtWidgets.QPushButton(self.centralwidget)
        self.addItem.setGeometry(QtCore.QRect(1090, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addItem.setFont(font)
        self.addItem.setAutoDefault(True)
        self.addItem.setDefault(True)
        self.addItem.setFlat(False)
        self.addItem.setObjectName("addItem")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 1241, 641))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.supplieView = QtWidgets.QTableWidget(self.tab)
        self.supplieView.setGeometry(QtCore.QRect(0, 0, 1231, 601))
        self.supplieView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.supplieView.setAlternatingRowColors(True)
        self.supplieView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.supplieView.setColumnCount(0)
        self.supplieView.setObjectName("supplieView")
        self.supplieView.setRowCount(0)
        self.supplieView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.item_info = QtWidgets.QTableWidget(self.tab_2)
        self.item_info.setGeometry(QtCore.QRect(0, 0, 1231, 601))
        self.item_info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.item_info.setAlternatingRowColors(True)
        self.item_info.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.item_info.setColumnCount(0)
        self.item_info.setObjectName("item_info")
        self.item_info.setRowCount(0)
        self.item_info.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabWidget.addTab(self.tab_2, "")
        Ms.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ms)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 21))
        self.menubar.setObjectName("menubar")
        Ms.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ms)
        self.statusbar.setObjectName("statusbar")
        Ms.setStatusBar(self.statusbar)

        self.retranslateUi(Ms)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Ms)

    def retranslateUi(self, Ms):
        _translate = QtCore.QCoreApplication.translate
        Ms.setWindowTitle(_translate("Ms", "Salary Relation Management"))
        self.addSupplier.setText(_translate("Ms", "Add Supplier"))
        self.label.setText(_translate("Ms", "Supplier Relation Management"))
        self.addItem.setText(_translate("Ms", "Add Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Ms", "Supplier"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Ms", "Items"))
        loadItemInfo.configure_table(self.item_info)
        loadSupplierInfo.configure_table(self.supplieView)
        dashboardBtnConfigs.addItem(self.addItem, lambda: loadItemInfo.renderTable(self.item_info))
        dashboardBtnConfigs.addSupplier(self.addSupplier, lambda: loadSupplierInfo.renderTable(self.supplieView))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ms = QtWidgets.QMainWindow()
    ui = Ui_Ms()
    ui.setupUi(Ms)
    Ms.show()
    sys.exit(app.exec_())