# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editSupplier.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Utils.database import database
from Utils import messageBox
from Components import supplierItemList


class Ui_Dialog(object):
    def setupUi(self, Dialog, callback, name, address, remarks, stat, sup_id):
        self.name = name
        self._address = address
        self._remarks = remarks
        self.stat = stat

        Dialog.setObjectName("Dialog")
        Dialog.resize(708, 292)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(False)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 671, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.supplier_name = QtWidgets.QLineEdit(Dialog)
        self.supplier_name.setMaxLength(100)
        self.supplier_name.setGeometry(QtCore.QRect(20, 40, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.supplier_name.setFont(font)
        self.supplier_name.setText("")
        self.supplier_name.setObjectName("supplier_name")
        self.address = QtWidgets.QLineEdit(Dialog)
        self.address.setMaxLength(150)
        self.address.setGeometry(QtCore.QRect(20, 110, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.address.setFont(font)
        self.address.setText("")
        self.address.setObjectName("address")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.remarks = QtWidgets.QLineEdit(Dialog)
        self.remarks.setMaxLength(150)
        self.remarks.setGeometry(QtCore.QRect(20, 170, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.remarks.setFont(font)
        self.remarks.setText("")
        self.remarks.setObjectName("remarks")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(20, 220, 221, 17))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.edit_btn = QtWidgets.QPushButton(Dialog)
        self.edit_btn.setGeometry(QtCore.QRect(620, 40, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_btn.setFont(font)
        self.edit_btn.setObjectName("edit_btn")
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setEnabled(False)
        self.cancel_btn.setGeometry(QtCore.QRect(620, 70, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.delete_btn = QtWidgets.QPushButton(Dialog)
        self.delete_btn.setGeometry(QtCore.QRect(620, 110, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("color: rgb(255, 102, 102)")
        self.delete_btn.setObjectName("delete_btn")

        self.back_btn = QtWidgets.QPushButton(Dialog)
        self.back_btn.setGeometry(QtCore.QRect(620, 170, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_btn.setFont(font)
        self.back_btn.setObjectName("back_btn")

        self.view_item_lists = QtWidgets.QPushButton(Dialog)
        self.view_item_lists.setGeometry(QtCore.QRect(445, 210, 250, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.view_item_lists.setFont(font)
        self.view_item_lists.setObjectName("view_item_lists")

        def _callback():
            attempt = database.execNonQuery('Update supplier_info set supplier_name = %s, address = %s, remarks = %s, stat = %s WHERE supp_id = %s'
                                            ,(self.supplier_name.text(), self.address.text(), self.remarks.text(), 1 if self.checkBox.isChecked() else 0, sup_id))
            
            if attempt:
                messageBox.Message("Success", "Supplier Edited Successfully")
            else:
                messageBox.Message("Fail", "Database Internal Error")

            callback()
            Dialog.accept()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(_callback) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.supplier_name.setText(name)
        self.address.setText(address)
        self.remarks.setText(remarks)
        self.checkBox.setChecked(stat == 1)
        self.supplier_name.setEnabled(False)
        self.address.setEnabled(False)
        self.remarks.setEnabled(False)
        self.checkBox.setEnabled(False)

        self.back_btn.clicked.connect(Dialog.reject)

        def edit_callback():
            self.supplier_name.setEnabled(True)
            self.address.setEnabled(True)
            self.remarks.setEnabled(True)
            self.checkBox.setEnabled(True)
            self.edit_btn.setEnabled(False)
            self.cancel_btn.setEnabled(True)
            self.buttonBox.setEnabled(True)
        self.edit_btn.clicked.connect(edit_callback)

        def cancel_edit_callback():
            self.supplier_name.setText(self.name)
            self.address.setText(self._address)
            self.remarks.setText(self._remarks)
            self.checkBox.setChecked(self.stat == 1)
            self.supplier_name.setEnabled(False)
            self.address.setEnabled(False)
            self.remarks.setEnabled(False)
            self.checkBox.setEnabled(False)
            self.edit_btn.setEnabled(True)
            self.cancel_btn.setEnabled(False)
            self.buttonBox.setEnabled(False)
        self.cancel_btn.clicked.connect(cancel_edit_callback)
        self.buttonBox.rejected.connect(cancel_edit_callback) # type: ignore

        def delete_callback():
            if(messageBox.show_warning_message("Delete Item", "Do you really want to delete\nthe item?")):
                
                if(database.execNonQuery('delete from supplier_item_lists where supp_id = %s', (sup_id, ))):
                    attempt = database.execNonQuery('Delete from supplier_info where supp_id = %s', (sup_id, ))

                    if attempt:
                        messageBox.Message("Success", "Supplier Deleted Successfully")
                    else:
                        messageBox.ErrorMessage("Fail", "Database Internal Error")
                else:
                    messageBox.ErrorMessage("Fail", "Database Internal Error")

                callback()
            Dialog.accept()
        self.delete_btn.clicked.connect(delete_callback)        
        self.view_item_lists.clicked.connect(lambda: supplierItemList.start(sup_id))
        # self.doubleSpinBox.setMaximum(2**32+0.99)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Supplier Settings"))
        self.label.setText(_translate("Dialog", "Supplier"))
        self.label_2.setText(_translate("Dialog", "Address"))
        self.label_3.setText(_translate("Dialog", "Remarks"))
        self.checkBox.setText(_translate("Dialog", "Active Supplier"))
        self.edit_btn.setText(_translate("Dialog", "Edit"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
        self.delete_btn.setText(_translate("Dialog", "Delete"))
        self.back_btn.setText(_translate("Dialog", "Back"))
        self.view_item_lists.setText(_translate("Dialog", "View Supplier Available Item/s"))


def start(callback: callable, name, address, remarks, stat, sup_id):
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, callback, name, address, remarks, stat, sup_id)
    Dialog.exec_()

