# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Utils.database import database
from Utils import messageBox


class Ui_EditItem(object):
    def setupUi(self, EditItem, callback: callable, name, price, item_id):
        self._ItemName = name
        self._price = price

        EditItem.setObjectName("EditItem")
        EditItem.resize(563, 244)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditItem)
        self.buttonBox.setGeometry(QtCore.QRect(10, 200, 441, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.ItemName = QtWidgets.QLineEdit(EditItem)
        self.ItemName.setMaxLength(100)
        self.ItemName.setGeometry(QtCore.QRect(20, 50, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ItemName.setFont(font)
        self.ItemName.setObjectName("ItemName")
        self.label = QtWidgets.QLabel(EditItem)
        self.label.setGeometry(QtCore.QRect(20, 30, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(EditItem)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(EditItem)
        self.doubleSpinBox.setGeometry(QtCore.QRect(20, 140, 421, 31))
        self.doubleSpinBox.setMaximum(1677216.99)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.back_btn = QtWidgets.QPushButton(EditItem)
        self.back_btn.setGeometry(QtCore.QRect(470, 160, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_btn.setFont(font)
        self.back_btn.setObjectName("back_btn")
        self.edit_btn = QtWidgets.QPushButton(EditItem)
        self.edit_btn.setGeometry(QtCore.QRect(470, 30, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_btn.setFont(font)
        self.edit_btn.setObjectName("edit_btn")
        self.cancel_btn = QtWidgets.QPushButton(EditItem)
        self.cancel_btn.setEnabled(False)
        self.cancel_btn.setGeometry(QtCore.QRect(470, 60, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.delete_btn = QtWidgets.QPushButton(EditItem)
        self.delete_btn.setGeometry(QtCore.QRect(470, 100, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("color: rgb(255, 102, 102)")
        self.delete_btn.setObjectName("delete_btn")

        def _callback():
            attempt = database.execNonQuery('UPDATE item_info SET name = %s, base_price = %s WHERE item_id = %s', (self.ItemName.text(), self.doubleSpinBox.text(), item_id))

            if attempt:
                messageBox.Message("Success", "Item Edited Successfully")
            else:
                messageBox.Message("Fail", "Database Internal Error")

            callback()
            EditItem.accept()

        self.retranslateUi(EditItem)
        self.buttonBox.accepted.connect(_callback) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditItem)

        self.ItemName.setText(self._ItemName)
        self.doubleSpinBox.setValue(float(self._price))
        self.buttonBox.setEnabled(False)
        self.ItemName.setEnabled(False)
        self.doubleSpinBox.setEnabled(False)

        def edit_callback():
            self.buttonBox.setEnabled(True)
            self.ItemName.setEnabled(True)
            self.doubleSpinBox.setEnabled(True)
            self.edit_btn.setEnabled(False)
            self.cancel_btn.setEnabled(True)
        self.edit_btn.clicked.connect(edit_callback)

        def cancel_edit_callback():
            self.ItemName.setText(self._ItemName)
            self.doubleSpinBox.setValue(float(self._price))
            self.buttonBox.setEnabled(False)
            self.ItemName.setEnabled(False)
            self.doubleSpinBox.setEnabled(False)
            self.edit_btn.setEnabled(True)
            self.cancel_btn.setEnabled(False)
        self.cancel_btn.clicked.connect(cancel_edit_callback)
        self.buttonBox.rejected.connect(cancel_edit_callback) # type: ignore
        self.back_btn.clicked.connect(EditItem.reject)

        def delete_callback():
            if(messageBox.show_warning_message("Delete Item", "Do you really want to delete\nthe item?")):

                if(int(database.execScalar('SELECT COUNT(*) FROM supplier_item_lists WHERE item_id = %s', (item_id))) > 0):
                    messageBox.ErrorMessage("Cannot Delete the Item", "The item has been enlisted of some suppliers.\nDelete the item from supplier info first before proceeding")
                    EditItem.accept()
                else:
                    attempt = database.execNonQuery('DELETE FROM item_info where item_id= %s', (item_id, ))

                    if attempt:
                        messageBox.Message("Success", "Supplier Deleted Successfully")
                    else:
                        messageBox.ErrorMessage("Fail", "Database Internal Error")

                callback()
            EditItem.accept()
        self.delete_btn.clicked.connect(delete_callback)

    def retranslateUi(self, EditItem):
        _translate = QtCore.QCoreApplication.translate
        EditItem.setWindowTitle(_translate("EditItem", "Add Item"))
        self.ItemName.setText(_translate("EditItem", "123"))
        self.label.setText(_translate("EditItem", "TextLabel"))
        self.label_2.setText(_translate("EditItem", "TextLabel"))
        self.back_btn.setText(_translate("EditItem", "Back"))
        self.edit_btn.setText(_translate("EditItem", "Edit"))
        self.cancel_btn.setText(_translate("EditItem", "Cancel"))
        self.delete_btn.setText(_translate("EditItem", "Delete"))


def start(callback: callable, name, price, item_id):
    Dialog = QtWidgets.QDialog()
    ui = Ui_EditItem()
    ui.setupUi(Dialog, callback, name, price, item_id)
    Dialog.exec_()
