# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editItemInSupplier.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Utils.database import database
from Utils import messageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog, callback, siid):
        self.siid = siid
        self.status = ['Unavailable', 'Available', 'Phased Out']
        self._callback = callback
        Dialog.setObjectName("Dialog")
        Dialog.resize(554, 257)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(False)
        self.buttonBox.setGeometry(QtCore.QRect(10, 220, 441, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(10, 10, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.edit_btn = QtWidgets.QPushButton(Dialog)
        self.edit_btn.setGeometry(QtCore.QRect(470, 20, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_btn.setFont(font)
        self.edit_btn.setObjectName("edit_btn")
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setEnabled(False)
        self.cancel_btn.setGeometry(QtCore.QRect(470, 50, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.delete_btn = QtWidgets.QPushButton(Dialog)
        self.delete_btn.setGeometry(QtCore.QRect(470, 110, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("color: rgb(255, 102, 102)")
        self.delete_btn.setObjectName("delete_btn")
        self.back_btn = QtWidgets.QPushButton(Dialog)
        self.back_btn.setGeometry(QtCore.QRect(470, 170, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_btn.setFont(font)
        self.back_btn.setObjectName("back_btn")
        self.qtLabel = QtWidgets.QLabel(Dialog)
        self.qtLabel.setGeometry(QtCore.QRect(30, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qtLabel.setFont(font)
        self.qtLabel.setObjectName("qtLabel")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 170, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.qtLabel_2 = QtWidgets.QLabel(Dialog)
        self.qtLabel_2.setGeometry(QtCore.QRect(30, 60, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.qtLabel_2.setFont(font)
        self.qtLabel_2.setObjectName("qtLabel_2")
        self.qtLabel_3 = QtWidgets.QLabel(Dialog)
        self.qtLabel_3.setGeometry(QtCore.QRect(30, 100, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.qtLabel_3.setFont(font)
        self.qtLabel_3.setObjectName("qtLabel_3")

        def _callback():
            attempt = database.execNonQuery('UPDATE supplier_item_lists set stat = %s where siid = %s', (self.comboBox.currentIndex(), self.siid))

            if attempt:
                messageBox.Message("Success", "Supplier Deleted Successfully")
            else:
                messageBox.Message("Fail", "Database Internal Error")

            callback()
            Dialog.accept()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(_callback) # type: ignore
        # self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        # self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "TextLabel"))
        self.edit_btn.setText(_translate("Dialog", "Edit"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
        self.delete_btn.setText(_translate("Dialog", "Delete"))
        self.back_btn.setText(_translate("Dialog", "Back"))
        self.qtLabel.setText(_translate("Dialog", "Item\'s Status"))

        data = database.fetchData("select 	siid,     item_info.`name`,     CONCAT('₱', FORMAT(item_info.base_price,2)) as Price,     supplier_info.supplier_name,     supplier_item_lists.stat from supplier_item_lists join item_info 	on supplier_item_lists.item_id = item_info.item_id join supplier_info 	on supplier_item_lists.supp_id = supplier_info.supp_id where siid = %s", (self.siid, ))[0]
        self.qtLabel_2.setText(_translate("Dialog", f"Item: {data['name']}"))
        self.qtLabel_3.setText(_translate("Dialog", f"Base Price: {data['Price']}"))
        self.comboBox.addItems(self.status)
        self._status = data['stat']
        self.comboBox.setCurrentIndex(self._status)
        
        self.edit_btn.setEnabled(True)
        self.cancel_btn.setEnabled(False)
        self.comboBox.setEnabled(False)

        def edit_callback():
            self.edit_btn.setEnabled(False)
            self.cancel_btn.setEnabled(True)
            self.comboBox.setEnabled(True)
            self.buttonBox.setEnabled(True)
        self.edit_btn.clicked.connect(edit_callback)

        def cancel_edit_callback():
            self.edit_btn.setEnabled(True)
            self.cancel_btn.setEnabled(False)
            self.comboBox.setEnabled(False)
            self.buttonBox.setEnabled(False)
        self.cancel_btn.clicked.connect(cancel_edit_callback)

        def delete_callback():
            if(messageBox.show_warning_message("Delete Item", "Do you really want to delete\nthe item from the supplier's item list?")):
                attempt = database.execNonQuery('Delete from supplier_item_lists where siid = %s', (self.siid, ))
                if attempt:
                    messageBox.Message("Success", "Supplier Deleted Successfully")
                else:
                    messageBox.Message("Fail", "Database Internal Error")
                self._callback()
                Dialog.accept()
        self.delete_btn.clicked.connect(delete_callback)
        self.back_btn.clicked.connect(Dialog.reject)
        self.buttonBox.rejected.connect(cancel_edit_callback) # type: ignore


def start(callback: callable, siid):
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, callback, siid)
    Dialog.exec_()