# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItemList.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Utils.database import database
from Backend import loadItemList
from Components import editItemInSupplier
from Utils import widgetTablesTools


class Ui_Dialog(object):
    def setupUi(self, Dialog, sup_id):
        self.sup_id = sup_id
        Dialog.setObjectName("Dialog")
        Dialog.resize(1252, 721)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(900, 680, 641, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(10, 10, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.supplieView = QtWidgets.QTableWidget(Dialog)
        self.supplieView.setGeometry(QtCore.QRect(10, 70, 1231, 611))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.supplieView.setFont(font)
        self.supplieView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.supplieView.setAlternatingRowColors(True)
        self.supplieView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.supplieView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.supplieView.setObjectName("supplieView")
        self.editItem_btn = QtWidgets.QPushButton(Dialog)
        self.editItem_btn.setGeometry(QtCore.QRect(1060, 10, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.editItem_btn.setFont(font)
        self.editItem_btn.setObjectName("editItem_btn")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Item List"))
        self.title.setText(_translate("Dialog", "TextLabel"))
        self.editItem_btn.setText(_translate("Dialog", "Add Item"))
        loadItemList.initial(self.title, self.sup_id, self.supplieView)
        loadItemList.setAddItem(self.sup_id, self.supplieView, self.editItem_btn)

        def supplieView_double_click_callback():
            siid = widgetTablesTools.get_selected_row_data(self.supplieView)[0][0]
            editItemInSupplier.start(lambda: loadItemList.renderTable(self.sup_id, self.supplieView), siid)
        self.supplieView.doubleClicked.connect(supplieView_double_click_callback)

def start(sup_id):
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, sup_id)
    Dialog.exec_()